port: 8080

tracing:
  enabled: true
  endpoint: "localhost:4318"

upstream:
  url: "http://localhost:1234"
  mode: "batch"
  batch_size: 2
  batch_timeout: 5s
  queue:
    max_size: 100
    request_max_age: 60s
    priorities:
      - name: high
        value: 0
        aliases: ["urgent", "critical", "p0"]
      - name: medium
        value: 1
        aliases: ["normal", "standard", "p1"]
        shed_at: 60
      - name: low
        value: 2
        aliases: ["background", "batch", "p2"]
        shed_at: 30

