port: 8080

tracing:
  enabled: true
  endpoint: "localhost:4318"

upstream:
  url: "http://localhost:1234"
  mode: "batch"
  batch_size: 2
  batch_timeout: 5s
  max_concurrent: 1
  queue:
    max_size: 100
    low_priority_shed_at: 30
    medium_priority_shed_at: 60
    request_max_age: 60s